version: '3.7'

services:
  django_gunicorn:
    volumes:
      - static:/static

    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

  db:
    image: postgres:12.0-alpine
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    command: -p 5433
    expose:
      - "5433"
    ports:
      - '5433:5433'



volumes:
  static:
  db:


